# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52b08b485b47c9bf5626a9413543dd45d18f59da3f2d988412d6ba22d5c987e17e1532e403a7b9956ee484617bc16be1f3c5474c2df7f3b884b50d34fbd51a41

test:
  secret_key_base: 18d7be4b6ae1129bd2d1a809886c10057391f5d861771b5dd0679f57babe6b409216f63c4c59bd3b1e7fe63a1165101155cac58c72f555c9b0b6eed6cd637fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
